package dev.jgunsett.inmobiliaria.application.mapper;

import java.util.List;

import org.springframework.stereotype.Component;

import dev.jgunsett.inmobiliaria.application.dto.invoice.InvoiceCreateRequest;
import dev.jgunsett.inmobiliaria.application.dto.invoice.InvoiceLineRequest;
import dev.jgunsett.inmobiliaria.application.dto.invoice.InvoiceLineResponse;
import dev.jgunsett.inmobiliaria.application.dto.invoice.InvoiceResponse;
import dev.jgunsett.inmobiliaria.domain.entity.Invoice;
import dev.jgunsett.inmobiliaria.domain.entity.InvoiceLine;

@Component
public class InvoiceMapper {

    // CreateRequest → Invoice (sin relaciones ni estado)
    public Invoice toEntity(InvoiceCreateRequest request) {

        return Invoice.builder()
                .date(request.getDate())
                .dueDate(request.getDueDate() != null
                        ? request.getDueDate()
                        : request.getDate().toLocalDate())
                .type(request.getType())
                .build();
    }

    // LineRequest → InvoiceLine
    public InvoiceLine toLineEntity(InvoiceLineRequest request, Invoice invoice) {

        InvoiceLine line = InvoiceLine.builder()
                .invoice(invoice)
                .concept(request.getConcept())
                .quantity(request.getQuantity())
                .unitPrice(request.getUnitPrice())
                .build();

        // El total de la factura se calcula antes de persistir las líneas,
        // por lo que el subtotal debe estar disponible en este momento.
        line.recalculateSubtotal();
        return line;
    }

    // Invoice → Response
    public InvoiceResponse toResponse(Invoice invoice) {

        return InvoiceResponse.builder()
                .id(invoice.getId())
                .code(invoice.getCode())
                .type(invoice.getType())
                .status(invoice.getStatus())
                .date(invoice.getDate())
                .dueDate(invoice.getDueDate())
                .total(invoice.getTotal())
                .lateFeeDailyPercentage(invoice.getLateFeeDailyPercentage())
                .customerId(invoice.getCustomer().getId())
                .customerFullName(invoice.getCustomer().getFullName())
                .contractId(
                        invoice.getContract() != null
                                ? invoice.getContract().getId()
                                : null
                )
                .contractName(
                        invoice.getContract() != null
                                ? invoice.getContract().getProperty().getName()
                                : null
                )
                .autoGenerated(invoice.getAutoGenerated())
                .billingPeriod(invoice.getBillingPeriod())
                .lines(
                        invoice.getLines()
                                .stream()
                                .map(this::toLineResponse)
                                .toList()
                )
                .creationDate(invoice.getCreationDate())
                .modificationDate(invoice.getModificationDate())
                .build();
    }

    // InvoiceLine → Response
    private InvoiceLineResponse toLineResponse(InvoiceLine line) {

        return InvoiceLineResponse.builder()
                .id(line.getId())
                .concept(line.getConcept())
                .quantity(line.getQuantity())
                .unitPrice(line.getUnitPrice())
                .subtotal(line.getSubtotal())
                .lateFee(line.getLateFee())
                .build();
    }
}
