package dev.jgunsett.inmobiliaria.application.service;

import dev.jgunsett.inmobiliaria.domain.entity.Contract;
import dev.jgunsett.inmobiliaria.domain.entity.Invoice;
import dev.jgunsett.inmobiliaria.domain.entity.InvoiceLine;
import dev.jgunsett.inmobiliaria.domain.enums.BillingFrequency;
import dev.jgunsett.inmobiliaria.domain.enums.ContractStatus;
import dev.jgunsett.inmobiliaria.domain.enums.InvoiceStatus;
import dev.jgunsett.inmobiliaria.domain.enums.InvoiceType;
import dev.jgunsett.inmobiliaria.repository.ContractRepository;
import dev.jgunsett.inmobiliaria.repository.InvoiceRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
public class AutoInvoiceGenerationService {

    private static final DateTimeFormatter PERIOD_FMT = DateTimeFormatter.ofPattern("yyyy-MM");

    private final ContractRepository contractRepository;
    private final InvoiceRepository invoiceRepository;
    private final ContractService contractService;
    private final SystemSettingService systemSettingService;

    @Transactional
    public int generateForCurrentPeriod() {
        try {
            String enabled = systemSettingService.findEntityByKey("invoice.auto-generation.enabled").getValue();
            if (!"true".equalsIgnoreCase(enabled)) {
                log.debug("Generación automática de facturas deshabilitada");
                return 0;
            }
        } catch (Exception ex) {
            log.debug("Setting invoice.auto-generation.enabled no encontrado, se omite generación");
            return 0;
        }

        YearMonth period = YearMonth.now();
        List<Contract> activeContracts = contractRepository
                .findByStatus(ContractStatus.ACTIVE, Pageable.unpaged())
                .getContent();

        int generated = 0;
        for (Contract contract : activeContracts) {
            try {
                if (generateForContract(contract, period)) {
                    generated++;
                }
            } catch (Exception ex) {
                log.warn("Error al generar factura automática para contrato #{}: {}", contract.getId(), ex.getMessage());
            }
        }
        log.info("Generación automática: {} facturas creadas para el período {}", generated, period);
        return generated;
    }

    private boolean generateForContract(Contract contract, YearMonth period) {
        if (!shouldGenerateForPeriod(contract, period)) {
            return false;
        }

        String periodStr = period.format(PERIOD_FMT);
        if (invoiceRepository.existsByContractIdAndBillingPeriod(contract.getId(), periodStr)) {
            return false;
        }

        BigDecimal amount = contractService.calculateRentalAmount(contract.getId(), period.atDay(1));

        Invoice invoice = Invoice.builder()
                .customer(contract.getTenant())
                .contract(contract)
                .type(InvoiceType.RENT)
                .status(InvoiceStatus.DRAFT)
                .date(LocalDateTime.now())
                .total(amount)
                .autoGenerated(true)
                .billingPeriod(periodStr)
                .code("INV-AUTO-" + LocalDateTime.now())
                .build();

        InvoiceLine line = InvoiceLine.builder()
                .invoice(invoice)
                .concept("Alquiler " + periodStr + " — " + contract.getProperty().getName())
                .quantity(1)
                .unitPrice(amount)
                .build();

        invoice.getLines().add(line);
        invoice.recalculateTotal();
        invoiceRepository.save(invoice);
        return true;
    }

    private boolean shouldGenerateForPeriod(Contract contract, YearMonth period) {
        BillingFrequency freq = contract.getBillingFrequency();
        if (freq == null || freq == BillingFrequency.MONTHLY) return true;

        LocalDate start = contract.getStartDate();
        if (start == null) return true;

        int monthsBetween = (int) java.time.temporal.ChronoUnit.MONTHS.between(
                YearMonth.from(start), period);

        return switch (freq) {
            case QUARTERLY -> monthsBetween % 3 == 0;
            case YEARLY -> monthsBetween % 12 == 0;
            default -> true;
        };
    }
}
